# -*- coding: utf-8 -*-
"""gta-car-ai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GelNyZcI_fIcAD6bbnBCxjs2AfxXOrNU
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/Projekty/dataset.zip

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

traindf = pd.read_csv('/content/dataset/balanced_data2.csv',dtype=str)

datagen=tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255.,validation_split=0.1)
train_generator=datagen.flow_from_dataframe(
dataframe=traindf,
directory="/content/dataset",
x_col= 'Id',
y_col=["Angle", "Throttle"],
subset="training",
batch_size=32,
seed=42,
shuffle=True,
class_mode="multi_output",
target_size=(384,160))

image_size = (384, 160)